### ISSUE TITLE
Footnote numbering in LaTeX template

### ISSUE THREAD

**Issue by HughP** [dcmi/dcpapers-templates#1]
Greetings @nishad 

I am using the LaTeX template. I am using the `\thanks{}` command and it produces the expected footnote with an asterix `*`.  However, following footnotes start at the number `2` rather than `1` when using the `\footonote{}` command.

Is there a way to restart the numbering at 1?

**Comment by nishad** [comment]
@HughP This is expected behavior since `\thanks` command is just `\footnote` with a different character for the number. So the other footnotes will continue with the numbering. 

To start the other footnotes with number '1', you can use `\setcounter{footnote}{0}` before the first section.

For example 

```latex

\keywords{metadata; evaluation; visual graphic analysis}

\setcounter{footnote}{0}

\section{Submission of papers to DC 2022}

```
